spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moneycookie
    username: moneycookie
    password: 1234

jwt:
  header-string: Authorization
  token-prefix: Bearer
  secret: xggxb8YtetDnjQ8p2kI6etnu3YZZD2QgD0TlQH4189yIIgMlT9HpbGohRiZmtbYw
  expiration-time: 864000000