spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moneycookie
    username: moneycookie
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id:
            client-secret: